### ISSUE TITLE
/api/1/payment/payout/bank always returns Invalid transaction signature, but it's correct

### ISSUE THREAD

**Issue by adastreamer** [globitex/api-samples#1]
Hello,

We try to run method `/api/1/payment/payout/bank`, but it always returns error. We have our own implementations in GoLang and Ruby, but finally tested using your code: https://github.com/globitex/api-samples/blob/master/rest/node-js/rest-api-sample.js

Could you please check if your code is correct?

Thank you.

**Comment by KristapsK-globitex** [comment]
Hi, there were issues around that time, they have been however resolved since. Thank you for pointing them out!
